### ISSUE TITLE
Enable/disable including creation date in the filename

### ISSUE THREAD

**Issue by crocodileDundee** [prose/prose#1008]
Hello, I've been swimming through the issues and I can't find an answer to this.

When you have a `title` field defined in your metadata:
Is there an easy way to tell prose to avoid including the date in the filename for files in a certain directory, yet keep including the date in the filename for files in another directory?

For example:
* `posts/` --> Include date (`YYYY-MM-DD-slug.md`)
* `foobar/` --> Don't include date(`slug.md`)

This is How I defined the title field in the metadata:
```yaml
    posts:
      - name: "title"
        field:
          label: "Title"
          element: "text"
```

I want to keep the title field declaration in the metadata, because if I remove it, when I create a new file, it will let me edit the filename, but the file will be saved with no title. Then I need a second commit to add the title. [See this issue](#664).
