### ISSUE TITLE
Support for optional/mandatory frontmatter

### ISSUE THREAD

**Issue by DennisAlund** [prose/prose#1011]
It would be great if there was a configuration support for optional/mandatory front matter.

```YML

 # Leaving the field empty stores 0
 - name: "regular_price"
        field:
          element: "number"
          mandatory: true # default
          label: "Regular price"

 # Leaving the field empty omits the property from frontmatter altogether
 - name: "special_price"
        field:
          element: "number"
          mandatory: false
          label: "Special price"
```

This would allow a number field to have a non-existing value, instead of defaulting to `0` if omitted.

In my use case we are having a regular price for events and an optional special price for our members. If the member price is set to `0` it means it's for free, but if it's set to `nil` it means that it's the same price as the regular price for member.
