### ISSUE TITLE
Default unchecked checkbox field

### ISSUE THREAD

**Issue by Sitebase** [prose/prose#1018]
It's not possible to have a default unchecked checkbox field by setting the value to `false`. 
If you try this in your `_prose.yml` config the checkbox will by default be checked.

```
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "false"
```

What does work is to set the value to empty string which results in a default unchecked checkbox.
