### ISSUE TITLE
Multipe metadata select/multiselect fields with reference to .jsonp file results in empty file overview

### ISSUE THREAD

**Issue by bert-bruggeman** [prose/prose#1021]
Multipe metadata select/multiselect fields with reference to .jsonp file results in empty file overview...
If I use the same .jsonp file for both fields it works, both jsonp files work when there's only 1 select/multiselect field...

**_config.yml:**
```
# Prose
prose:
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "links"
        field:
          element: "multiselect"
          label: "Links"
          placeholder: "Select links"
          options: 'https://mysite.github.io/links.jsonp'
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          placeholder: "Select tags"
          options:  'https://mysite.github.io/tags.jsonp'
```
