### ISSUE TITLE
Bad yaml parser for prose configuration

### ISSUE THREAD

**Issue by jpeg729** [prose/prose#1032]
This works...
```yaml
prose:
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
```

This doesn't...

```yaml
prose:
  metadata:
    _posts:
      - name: "layout"
        field:
          - element: "hidden"
          - value: "blog"
```

Both are valid yaml
