### ISSUE TITLE
New issue introduced after today's commits (10/25)

### ISSUE THREAD

**Issue by AJGarrett** [prose/prose#1052]
@dereklieu Not sure if you can assist, but saw that you made a few commits and merged some PRs today, so thought I'd share with you and the team.   

We use prose to post content to a non-Jekyll site.    As of this afternoon, when we navigate to our prose.io site, it no longer reads our config file.   We see no files when logged in, and unable to creat new files either.

I'm seeing the following errors in the console:
```
Uncaught TypeError: n.indexOf is not a function
    at i (prose.js:1)
    at prose.js:2
    at Array.forEach (<anonymous>)
    at Function.S.each.S.forEach (prose.js:37)
    at prose.js:2
    at t (prose.js:37)
    at Object.defer (prose.js:37)
    at prose.js:2
    at Function.S.each.S.forEach (prose.js:37)
    at n.parseConfig (prose.js:2)
```

Here's our _prose.yml:

```
prose:
  rooturl: 'src/content'
  siteurl: 'http://athletesinaction.org'
  relativeLinks: 'http://athletesinaction.org'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    src/content:
      - name: "title"
        field:
          label: "Title"
          element: "text"
          help: "70 Character Max for Google and Social Media"
      - name: "summary"
        field:
            label: "Summary"
            element: "text"
      - name: "slug"
        field: 
          label: "URL of Page"
          element: "text"
          help: "should be the title, with dashed insterted instead of spaces"
      - name: "date"
        field:
          label: "date"
          help: "YYYY-MM-DD"
          element: "text"
      - name: "type"
        field:
          label: "Post Type"
          element: "select"
          options:
            - name: "Under Review"
              value: "underreview"
            - name: "Playbook"
              value: "devotion"
            - name: "Quickhit"
              value: "quickhit"
            - name: "Workout"
              value: "workout"
            - name: "InnerView"
              value: "innerview"
      - name: "author"
        field: 
          label: "Author"
          element: "text"
          help: "i.e.  First Last"
      - name: "keywords"
        field: 
          label: "Keywords"
          element: "text"
          help: "tags,seperarted,by, commas"
      - name: "color"
        field: 
          label: "Primary Color"
          element: "text"
          help: "don't add a #'"
      - name: "image"
        field: 
          label: "Image File Name"
          element: "text"
          help: "do not include path"
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          help: "Leaving unchecked will hide the file from the index and archive pages."
          value: true
    src/content/quickhits:
      - name: "title"
        field:
          label: "Title"
          element: "text"
          help: "70 Character Max for Google and Social Media"
      - name: "summary"
        field:
            label: "Summary"
            element: "text"
      - name: "slug"
        field: 
          label: "URL of Page"
          element: "text"
          help: "should be the title, with dashed insterted instead of spaces"
      - name: "date"
        field:
          label: "date"
          help: "YYYY-MM-DD"
          element: "text"
      - name: "type"
        field:
          element: "hidden"
          value: "quickhit"          
      - name: "author"
        field: 
          label: "Author"
          element: "text"
          help: "i.e.  First Last"
      - name: "keywords"
        field: 
          label: "Keywords"
          element: "text"
          help: "tags,seperarted,by, commas"
      - name: "image"
        field: 
          label: "Image File Name"
          element: "text"
          help: "Do not include path to the image.  Square and Rectangle version of the image should have the same filename."
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          help: "Leaving unchecked will hide the file from the index and archive pages."
          value: true
```
