### ISSUE TITLE
Root url config

### ISSUE THREAD

**Issue by dfcreative** [prose/prose#1056]
I have [`_config.yml`](https://github.com/Yubisay/SCAC/blob/master/_config.yml) for prose set up so that it enables metafields for the root folder:

```yml
...
prose:
  rooturl: ''
  siteurl: 'http://yubisay.github.io/scac'
  media: 'assets'
  metadata:
    '':
      - name: "title"
        field:
          element: "text"
          label: "Title"
          type: "text"
      ...
```

Metafields for pages in root folder work fine, the problem comes when I try to create a new file via prose and save it:

![image](https://user-images.githubusercontent.com/300067/32305643-1db7f508-bf4d-11e7-9a58-264ed4a6a26b.png)
![image](https://user-images.githubusercontent.com/300067/32305637-163acb20-bf4d-11e7-9f6f-3601e7a87f6f.png)
![image](https://user-images.githubusercontent.com/300067/32305672-3b57818c-bf4d-11e7-8ec4-ad7769666903.png)
and the URL is
`https://api.github.com/repos/Yubisay/SCAC/contents//2017-11-01-sample.md?ref=master`

Here you see it inserts bad github API call.
What may be wrong with it or how can I resetup it?
