### ISSUE TITLE
Support for nested for loops

### ISSUE THREAD

**Issue by carolineolivia** [prose/prose#1091]
I have a collection with nested for loops like this
```
title: name
published: true
dates:
  - startdate: May 1st 2019
     sub-dates:
     - title: May 5th
     - title: May 8th
  - startdate: February 6th 2020
     sub-dates:
     - title: Februrary 8th
     - title: Februrary 8th
```
I have set it up in prose to be a multiselect, but it reads it as
`[object Object]`

![image](https://user-images.githubusercontent.com/17065639/65876346-51911c80-e389-11e9-8e6a-cc1615923a89.png)

Is there no support for nested for loops?
