### ISSUE TITLE
prose has stopped uploading to media folder instead its's using _posts

### ISSUE THREAD

**Issue by solrevdev** [prose/prose#1094]
Today I used the prose editor which uploaded some images but instead of them going to the `media` folder that I have set in config it instead ignored that and uploaded to the current `_posts` directory.

The only change I've made recently that may have anything to do with it is that the bottom my config file went from this 

```yaml
prose: 
  siteurl: 'https://solrevdev.com' 
  media: 'media'
```

to this 

```yaml
prose: 
  siteurl: 'https://solrevdev.com' 
  media: 'media'
  
github: [metadata]
```

My full config is [here if needed](https://github.com/solrevdev/solrevdev.github.io/blob/master/_config.yml).
