### ISSUE TITLE
Remove automatic published: true tag in _posts

### ISSUE THREAD

**Issue by vectorcrumb** [prose/prose#1097]
Is there any way to not set this tag automatically when publishing? I got my _config.yml from the starter template but don't have any mentions to `published`. I'm trying to edit my sites in `_posts`. When publishing, I get the following in my front matter:

```
---
title: Welcome to Jekyll!
categories:
  - Blog
tags:
  - Jekyll
  - update
+ published: true
---
```
My `_config.yml` file has the following `prose:` section:
```
prose:
  rooturl: '_posts'
  siteurl: 'https://sitename/'
  relativeLinks: 'https://sitename/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
            - name: "Pears"
              value: "pears"
            - name: "Mangos"
              value: "mangos"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
```
