### ISSUE TITLE
MetaData specify subkeys

### ISSUE THREAD

**Issue by Eun** [prose/prose#1100]
Is it possible to use the metadata to specify a subkey e.g. having the following structure:
```
---
title: "Art"
date: 2020-06-10T12:52:25Z
draft: false
mainmenu:
  name: "art"
  weight: 70
---
```

If not I propose a solution like
```
      - name: 
          mainmenu: name
        field:
          label: "Menu"
          element: "text"
          default: "art"
```

Alternatively 

```
      - name: mainmenu/name
        field:
          label: "Menu"
          element: "text"
          default: "art"
```
or 
```
      - name: mainmenu.name
        field:
          label: "Menu"
          element: "text"
          default: "art"
```

However the last two require nasty string splitting and yaml supports slashes and dots inside a string so it could break some configuration.
