### ISSUE TITLE
[FEAT] Add config.prose Support for File Editing Rules & Validation

### ISSUE THREAD

**Issue by SurajRaika** [prose/prose#1161]
## 🔧 Feature: Configurable Content Rules with config.prose File
Introduce support for a .prose/config.yaml (or config.prose) file to define per-file editing rules and behavior. This gives users fine-grained control over how files can be edited, validated, or protected.

Example Schema:

```yaml
# .prose/config.yaml or config.prose
rules:
  "*.md":
    requiredFrontMatter:
      - title
      - date
      - description
    disallowEdits: false
  "README.md":
    disallowDelete: true
    lockFrontMatter: true
  "*.json":
    schemaValidation: "./schemas/mySchema.json"
```
