### ISSUE TITLE
YAML parsing issues

### ISSUE THREAD

**Issue by michael** [prose/prose#195]
This blows up our YAML parser. Investigate why.

``` yml
markdown: kramdown
paygments: true
safe: false
permalink: /:year/:month/:title/ 
exclude: ["README.md"]
auto: true

title : Coding My Simple Life
author : 
  full_name : Harry Dong
  name : hdwills
  email : harrydeng2008@gmail.com
  github : hdwills
  twitter : @hdlifes

production_url : http://hdwills.github.com
```
