### ISSUE TITLE
Feature request: ability to specify date=NOW in metadata settings

### ISSUE THREAD

**Issue by darvin** [prose/prose#277]
``` yaml
#prose.io settings
prose:
  rooturl: "source"
  metadata:
    "source/_posts": |
      layout: post
      title: "Title"
      date: 2012-12-22 14:07
      comments: true
      categories: 
      published: true
```

I would like to be able to specify `date: CURRENT` or something and have this field autogenerated on document creation. or just point me on place to implement this
