### ISSUE TITLE
Metadata: hard defaults? (element: hidden?")

### ISSUE THREAD

**Issue by michael** [prose/prose#413]
@tristen Is there a way to set hard defaults to some metadata values (so the user doesn't see them)

E.g. I'd like to use that for for the categories entry, so every post gets assigned the specified category, without exposing that to the user.

Something like this:

```
  metadata:
    "_posts/projects":
      - name: "categories"
        field:
          element: "hidden"
          value: "projects"
    "_posts/people":
      - name: "categories"
        field:
          element: "hidden"
          value: "people"
```

So the resulting output would be for posts in the projects folder:

``` yml
categories:
- projects
```

And for those in the people folder:

``` yml
categories:
- people
```
