### ISSUE TITLE
metadata variable for user

### ISSUE THREAD

**Issue by parezcoydigo** [prose/prose#557]
Prose's configuration options provide a variable for CURRENT_DATETIME. I would like another variable that returns the username of the logged in user. For a blog with multiple contributors, this would allow a hidden metadata element along these lines:

```
- name: "author"
  field:
    element: "hidden"
    value: USER
```

So, for a repo with multiple collaborators, a post's author metadata can be automatically populated.
