### ISSUE TITLE
Date metadata value saved multiple times

### ISSUE THREAD

**Issue by jamiefolsom** [prose/prose#581]
I've added explicit date fields/values to all of my posts, to allow them to be edited via prose (to allow editors to control sorting). Now prose appears to be adding the same date to the date field as an array value in the frontmatter each time a post is edited.

sample frontmatter:

```
date: 
  - 2013-01-01T11:59:59.000Z
  - "Tue Jan 01 2013 06:59:59 GMT-0500 (EST)"
  - "Tue Jan 01 2013 06:59:59 GMT-0500 (EST),Tue Jan 01 2013 06:59:59 GMT-0500 (EST)"
```

_config.yml:

```
      - name: "date"
        field:
          element: "text"
          label: "Order"
          placeholder: "Enter a date in the form 2013-01-01 to order this slide in the hero"
```
