### ISSUE TITLE
textarea values not saved

### ISSUE THREAD

**Issue by jueyang** [prose/prose#582]
I set up a few `textarea` fields with the intention to take a list of items. It doesn't seem to keep the value when I want to modify a committed post. When I modify a field and save it again, all the textarea values are set back to `null`.

In my yml I have:

```
      - name: "performers"
        field:
          element: "textarea"
          label: "Performers"
          value: ""
```

The actual post has:

```
performers: 
  - Bridget Garwood
  - Paul Horan
  - Jasmin Johnson
  - Chris Keener
```
