### ISSUE TITLE
Can you apply metadata to the whole project?

### ISSUE THREAD

**Issue by okayjeffrey** [prose/prose#588]
I am writing a static site in jekyll and actually not using the _posts directory at all, so the /index.html I made /index.md so it is pretty important to the project so the client can edit it. 

I am trying to figure it out but not working any way I try. I am fairly new to yaml frontmatter, so I am bumping around a little but I'm fairly sure I have tried this all possible ways.

```
metadata:
- name: "layout"
  field:
    element: "hidden"
    value: "default"
- name: "index"
  field:
    element: "text"
    value: ""
    label: "Index"
- name: "hero"
  field:
    element: "text"
    value: ""
    label: "Title"
    placeholder: "This is the Main Text"

metadata:
/:
- name: "layout"
  field:
    element: "hidden"
    value: "default"
- name: "index"
  field:
    element: "text"
    value: ""
    label: "Index"
- name: "hero"
  field:
    element: "text"
    value: ""
    label: "Title"
    placeholder: "This is the Main Text"
```
