### ISSUE TITLE
Add helper text option to metadata form fields

### ISSUE THREAD

**Issue by samanpwbb** [prose/prose#603]
This would be _really_ nice to have:

![screen shot 2013-09-22 at 11 06 34 am](https://f.cloud.github.com/assets/108094/1187773/9a40f020-2398-11e3-9660-63113929b380.png)

Would be implemented like this: 

```
  - name: "tags"
    field:
      element: "multiselect"
      label: "Add Tags"
      help: "If you want the post to be linked to others in the series, remember to add the series name as a tag."
      placeholder: "Choose Tags"
      alterable: true
```

I might even try to do it...
