### ISSUE TITLE
Prose.io freezes on opening malformed? _config.yaml

### ISSUE THREAD

**Issue by josephfinlayson** [prose/prose#615]
Steps to reproduce:

Issue: console displays "Uncaught JS-YAML: can not read an implicit mapping pair; a colon is missed at line 13, column 14:
     description:
                       ^ 
and page is as below
1. Navigate to prose.io
2. Open my organisation (CDVC)
3. Organisation displays no files
4. Try to open _config.yml from history

Issue appears.

![image](https://f.cloud.github.com/assets/1572410/1279375/fa420f92-2f35-11e3-9778-374749c0a057.png)

_config.yml:

``` YAML
cdvcDetails:
 name: Cassian de Vere Cole Fine Art
 addressLineOne: abcs

exhibitionDetails:
 context: "Exhibition Details:"
 title: "GEORGINA von ETZDORF : PAINTINGS"
 dates: "Revised dates : 27th November - 14th December 2013"
 extraInfo: "Please contact the gallery for viewing times"

image: 
 location:
 description:
```
