### ISSUE TITLE
Checkbox in metadata does not display the label

### ISSUE THREAD

**Issue by jeremi** [prose/prose#622]
```
  metadata:
    _posts/articles:
      - name: "category"
        field:
          element: "hidden"
          value: "articles"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          value: ""
      - name: "published"
        label: "Published"
        value: false
        field:
          element: "checkbox"
      - name: "comments"
        label: "Comments"
        value: true
        field:
          element: "checkbox"
```

![editing _posts_articles_2013-10-18-your-filename md_2013-10-18-your-filename md at gh-pages prose](https://f.cloud.github.com/assets/9537/1359319/791bd8a0-37da-11e3-9b88-f0dcb58eba3d.png)
