### ISSUE TITLE
"Insert Link" value for "title" cannot be changed

### ISSUE THREAD

**Issue by antitoxic** [prose/prose#639]
I have this in my _config.yml:

``` yaml
prose:
  rooturl: "_posts"
  metadata:
    "_posts": |
      layout: post
      title: Среща с ...
      category: meeting
      tags: []
```

The bug is in 2 parts:
1. When I click "Insert Link" and I dont enter anything for "title" , it always defaults to my `metadata>_posts>title` 
2. When I click "Insert Link" and I do enter somethin for "title" the generated markdown still has my  `metadata>_posts>title`  and not my entered custom title.
