### ISSUE TITLE
nested metadata

### ISSUE THREAD

**Issue by xslim** [prose/prose#662]
I have in my metadata YAML

``` yaml

---
date: '2014-01-20'
categories: [articles, sailing]
image:
  thumb: isailor.jpg 

---
```

How do I define the `image.thumb` thing in `_config.yml`?
