### ISSUE TITLE
Can't configure file path/name when having title in metadata

### ISSUE THREAD

**Issue by oblitum** [prose/prose#664]
I have the following Prose configuration in my `_config.yml`:

``` yml
prose:
  ignore:
    - /\..*
    - /_config.yml
    - /atom.xml
    - /LICENSE.md
    - /_layouts
    - /_includes
    - /public
  metadata:
    "":
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
```

Before adding the `title` front matter field, I could set file name (and path including folders) of a new file. The file was being created without title, so I added the metadata `title`, which I need in front matter. Now when creating a new file in Prose, when previously I was setting the file name, now there's the place to fill the title, but I'm unable to properly set a file name/path anymore it seems?

Any help?
