### ISSUE TITLE
Feature Request : Auto-incrementing number field

### ISSUE THREAD

**Issue by jmatsushita** [prose/prose#675]
We're using Prose as a front-end for our users and generating content that is used in a mobile application. To facilitate the download of the latest version of the content on the mobile app, we use a versioning system which relies on incrementing numbers for posts (and some custom jekyll/liquid templates).

For this reason, it would be extremely helpful to have a prose metadata variable (such as the CURRENT_DATETIME variable or a specific autoincrement type for the number field) which would autoincrement. The configuration could for instance look like:

```
    _posts:
      - name: "version"
        field:
          element: "number"
          label: "Version"
          type: autoincrement
          alterable: no
```
