### ISSUE TITLE
Metadata fields not showing

### ISSUE THREAD

**Issue by ndarville** [prose/prose#715]
Here is the code: https://github.com/ndarville/ndarville.github.io/blob/763e5282508788cbbd0817754eb672d38328ad04/_config.yml#L26-L53.

Can’t see why it wouldn’t work. The ignore list works perfectly.

Tried with empty values as well: https://github.com/ndarville/ndarville.github.io/blob/36722415a518ca6af40899fd57057a77c7a6eb78/_config.yml#L26-L58.

**Comment by fulldecent** [comment]
Hello and thank you for this issue report. There have been several point releases in Prose since this issue was opened and there has not been much discussion here. I wanted to ask if you could please assist in confirming this is still an issue in the latest version of the product. If it is fixed, please close this issue :-)

Also, if possible could you please

  * Find out if this only affects certain browsers
  * Create a test case -- a list of steps we can perform to reproduce the problem
  * Enable web developer extensions and report the Javascript error message. And when in doubt, be over-descriptive of the bug and how you discovered it.

Since this project is looking for new maintainers (#743), it will be helpful if users can double check the old issues and delete ones that are fixed. This will be super helpful for the new team that works on moving this project forward.

I'm sorry this message is impersonal. And thanks for your help!

**Comment by ndarville** [comment]
@fulldecent:

It’s been a while, but I believe I followed the same steps:

![screen shot 2015-02-05 at 16 04 36](https://cloud.githubusercontent.com/assets/198682/6062531/c5e87fca-ad50-11e4-8981-3bed5264a44f.png)

1. `+` It now displays fields instead of raw metadata.
2. `-` Judging by my config file, it seems some hidden fields like `id` are shown:

    ```yaml
    prose:
        siteurl: 'https://ndarville.github.io'
        metadata:
            _drafts:
                - name: layout
                  field:
                      element: hidden
                      value: post
                - name: categories
                  field:
                      element: hidden
                      value: blog
                - name: title
                  field:
                      element: text
                - name: date
                  field:
                      element: hidden
                - name: excerpt
                  field:
                      element: text
                      placeholder: Use 200 characters at most.
                - name: id
                  field:
                      element: hidden
                - name: tags
                  field:
                      element: hidden
    ```

It’s been a really, really, really long time since I last used Prose, so your knowledge of how the config is supposed to work is without a doubt fresher than mine, so I’ll leave it to you to assess whether I am getting the right result based on my config. :)

I’ll have more time to look into this over the weekend, but for for now, this is as exhaustively as I can revisit the issue.
