### ISSUE TITLE
Allow editor width to be adjusted

### ISSUE THREAD

**Issue by JakeGinnivan** [prose/prose#717]
Making the following change to limiter makes the editing experience much nicer. It would be cool to allow this to be toggled, fixed vs dynamic width

```css
.containment, .limiter {
position: relative;
/* width: 90%; */
margin: 0 100px;
}
```
