### ISSUE TITLE
Allow configuration of different "new post" content by content type

### ISSUE THREAD

**Issue by davidascher** [prose/prose#791]
I have a site which has two kinds of content types (Jekyll collections). I'd like the "default text" for each to be specific (and forego the localization of said content).  I assume it's possible, but I can't find it in the wiki or in any of the sample configs.

**Comment by dawaltconley** [comment]
Would like to second this request; I imagine it would be simple to organize it like the metadata config, could also allow for other options:

```
defaults:
  _posts:
    text: |
      Enter your post here in Markdown.
  _data:
    file: yml
    text: |
      Enter data here in YAML.
```
