### ISSUE TITLE
Unpublished/published toggle (in toolbar) does not update frontmatter

### ISSUE THREAD

**Issue by tomsabin** [prose/prose#854]
Toggling between unpublished and published in the toolbar does not update the frontmatter data. When you click on the commit button and see a preview of your changes, nothing has been changed.

I have tried to trace through where this is caused and can see that the [`togglePublishing`](https://github.com/prose/prose/blob/master/app/views/toolbar.js#L311:L364) function works as expected (flipping the boolean value), but as soon as [`makeDirty`](https://github.com/prose/prose/blob/master/app/views/file.js#L830:L848) is called, the `metadata` on the model is reset by [`this.metadataEditor.getValue()`](https://github.com/prose/prose/blob/master/app/views/file.js#L840).

This is the frontmatter that I am using:
```
---
layout: blog
date: "2015-07-31 15:10 +0100"
published: false
title: Unpublished blog post
author: Tom Sabin
---
```

In my `_prose.yml` config I have a published checkbox, but I can't think how this could affect this toggle.
```
- name: 'published'
  field:
    element: 'checkbox'
    label: 'Published?'
    help: 'Published by default'
    value: true
```
