### ISSUE TITLE
How to handle nested YAML

### ISSUE THREAD

**Issue by jdsimcoe** [prose/prose#857]
I have a YAML setting that is nested. How would I represent this in Prose `_config.yml`. Here is my YAML config in my content files:

```yaml
---
sitemap:
  exclude: no
---
```

**Comment by dereklieu** [comment]
Hey @jdsimcoe, I don't think Prose supports groupings or sub-categories for metadata. The only way I can think of would be:

```(yaml)
- name: "sitemap-exclude"
  field:
    element: "checkbox"
    label: "Include sitemap"
    value: true
```

You could also try the raw metadata editor, although currently it's a little buggy.

**Comment by jdsimcoe** [comment]
Ok @dereklieu I changed things around but now Prose isn't identify the metadata to link in my Markdown files.

Here is `YAML` code in my `about.md` file:

```yaml
---
layout: page
published: true
title: About Us
og_title: About Circle
description: At Circle we are all about family.
og_description: At Circle we are all about family.
image: /source/media/apiary.png
og_image: /source/media/apiary.png
nav: secondary
order: 1
sitemap_exclude: no
---
```

Here is my `_config.yml` Prose section:

```yaml
# Prose
prose:
  rooturl: 'source'
  siteurl: 'http://meetcircle.co/'
  relativeLinks: 'http://meetcircle.co/links.jsonp'
  media: 'source/media'
  ignore:
    - source/public/
    - source/_includes
    - source/_layouts
    - _sass
    - source/blog
    - source/404.html
    - .gitignore
    - _config.yml
    - source/atom.xml
    - source/links.jsonp
    - source/sitemap.xml
    - source/styles.scss
  metadata:
    source/_posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
    source:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Create a Title for the Menu and Browser"
          value: ""
      - name: "og_title"
        field:
          element: "text"
          label: "Open Graph: Title"
          placeholder: "Create a title for social media"
          value: ""
      - name: "description"
        field:
          element: "textarea"
          label: "Description"
          placeholder: "Create a description for <meta> tags"
          value: ""
      - name: "og_description"
        field:
          element: "textarea"
          label: "Open Graph: Description"
          placeholder: "Create a description for social media"
          value: ""
      - name: "image"
        field:
          element: "text"
          label: "Hero Image"
          placeholder: "Specify a relative URI for a hero image"
          value: ""
      - name: "og_image"
        field:
          element: "text"
          label: "Open Graph: Image"
          placeholder: "Specify a relative URI for a social media image"
          value: ""
      - name: "nav"
        field:
          element: "select"
          label: "Navigation Type"
          placeholder: "Choose a navigation type"
          options:
            - name: "None"
              value: "none"
            - name: "Primary"
              value: "primary"
            - name: "Secondary"
              value: "secondary"
            - name: "Support"
              value: "support"
      - name: "order"
        field:
          element: "select"
          label: "Nav Order"
          placeholder: "Choose this page's order in navigation"
          options:
            - name: "0"
              value: "0"
            - name: "1"
              value: "1"
            - name: "2"
              value: "2"
            - name: "3"
              value: "3"
            - name: "4"
              value: "4"
            - name: "5"
              value: "5"
            - name: "6"
              value: "6"
            - name: "7"
              value: "7"
            - name: "8"
              value: "8"
            - name: "9"
              value: "9"
            - name: "10"
              value: "10"
      - name: "sitemap_exclude"
        field:
          element: "button"
          label: "Exclude from Sitemap"
          help: "Click this button to exclude this page from your sitemap.xml"
          on: "yes"
          off: "no"
```

Do you know why the metadata editor wouldn't be showing up?
