### ISSUE TITLE
Date breaking build (slightly different than previous date breaking issues) 

### ISSUE THREAD

**Issue by rdwatters** [prose/prose#880]
I'm playing with prose on a Jekyll test site that can be found at rdwatters.github.io. I currently sort my posts by the date: field in a post's metadata. That said, I only use the year, month, and date (eg, 2015-09-01).  This doesn't cause any issues for sorting on local dev, but because prose.io saves the full date (ie, including, h, s, etc), my builds are breaking when I update posts in prose. I would like to have the option for two separate dates in the metadata--one for publish_date (ie, the date that writes to the page, since this gives editors more control over what end-users see) and one for date (maintained by Jekyll/prose auto-magically. However, my attempt at a workaround to use publish_date resulted in prose doing the same thing w/r/t adding the full date automatically. Am I missing something in the config? I would like for authors to be able to change these dates at will. Thanks!

**Comment by dereklieu** [comment]
@rdwatters we do need to create a date metadata field - see #760. In the meantime, the best stopgap is to manage your date using a text element. You can pair this with a hidden element containing the creation date as below. 

```(yml)
- name: "creation_date"
  field:
    element: "hidden"
    value: "CURRENT_DATETIME"
- name: "publish_date"
  field:
    element: "text"
    placeholder: "yyyy-mm-dd"
```

**Comment by rdwatters** [comment]
Dereklieu, thanks so much for the quick response on this. I'll attempt the workaround this evening and get back to you. Any thoughts on an ETA for the data metadata field? Cheers.

**Comment by dereklieu** [comment]
@rdwatters great. Not sure on ETA, there's a couple of things I've been meaning to work on but if I have time over the long weekend I'll try to get to it.

**Comment by rdwatters** [comment]
@dereklieu So, as it turns out, the above workaround doesn't actually work. I created a published_on and a created date per your suggestion:

```yaml
metadata:
    _articles:
      - name: "updated_date"
        field:
          element: "hidden"
          value: "CURRENT_DATETIME"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Enter the title of this article"
          value: ""
      - name: "description"
        field:
          element: "textarea"
          label: "Article Description"
          help: "Write a short description of this article. Try to keep it to less than 200 characters."
      - name: "published_on"
        field:
          label: "When this article was published"
          element: "text"
          placeholder: "Enter as yyyy-mm-dd"
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish now"
          help: "Keep this unchecked if you do not want to   publish the article right now"
          value: "true"
      - name: "layout"
        field: 
          element: "hidden"
          value: "article"
      - name: "main_image"
        field:
          element: "text"
          label: "Article image"
          value: "Full filename of the image you want to use"
      - name: "main_image_description"
        field:
          element: "text"
          label: "Article image description"
        value: "Write a descrption of the image used for the   article"
      - name: "comments"
        field:
          element: "checkbox"
          label: "Include comments?"
          value: "true"
      - name: "insearch"
        field:
          element: "checkbox"
          label: "Include in search?"
          value: "true"
```

I am able to sort on the `published_on` date, but the problem is that when I enter a date as a string, it writes the metadata to the file in quotes; e.g., writing `2015-08-10` into the field in the prose editor writes `published_on: "2015-08-10"` to the markdown file, which then breaks the Jekyll build. When I open the same document again in prose and open the metadata, that field will then contain the full date, including seconds and hours. Any thoughts on this?
