### ISSUE TITLE
Only the last 7 fields from the configuration are included in the frontmatter

### ISSUE THREAD

**Issue by tomsabin** [prose/prose#893]
I am trying to add a number of different hidden/visible fields to the config file, however it seems there is a limit of 7 fields including a maximum of 1 hidden field.

This is what I was hoping to use in my config file:

```YML
prose:
  rooturl: 'source/blog'
  ignore: '.keep'
  media: 'source/blog/images'
  metadata:
    source/blog:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'blog'

      - name: 'title'
        field:
          element: 'text'
          label: 'title'

      - name: 'date'
        field:
          element: 'hidden'
          value: CURRENT_DATETIME

      - name: 'published'
        field:
          element: 'hidden'
          value: true

      - name: 'author'
        field:
          element: 'text'
          label: '* Author'
          help: 'Full name of the author (e.g. Tom Sabin) (required)'

      - name: 'tags'
        field:
          element: 'multiselect'
          label: 'Tags'
          help: 'Choose relevant tags (optional)'
          alterable: false
          options: [
            'Agile',
            'Culture',
            'Design',
            'Events',
            'Innovation',
            'Lean',
            'Rails' ]

      - name: 'main_image'
        field:
          element: 'text'
          label: 'Main blog image URL'
          help: 'The image that is shown on the blog listing page (optional)'

      - name: 'weekly_roundup'
        field:
          element: 'checkbox'
          label: 'Weekly roundup?'
          value: false
          help: '(optional)'
```

Produces:
```YML
---
published: true
author: Tom Sabin
tags: 
  - Agile
main_image: "https://upload.wikimedia.org/wikipedia/commons/1/1e/Large_Siamese_cat_tosses_a_mouse.jpg"
weekly_roundup: false
title: Blog post title
---
```

However, I have had to remove one of the fields, and make two hidden fields visible in order for the frontmatter to render correctly. With the above example, the `date` and `layout` were disregarded.

This is now what I have working:

```YML
prose:
  rooturl: 'source/blog'
  ignore: '.keep'
  media: 'source/blog/images'
  metadata:
    source/blog:

      - name: 'title'
        field:
          element: 'text'
          label: 'title'

      - name: 'author'
        field:
          element: 'text'
          label: '* Author'
          help: 'Full name of the author (e.g. Tom Sabin) (required)'

      - name: 'tags'
        field:
          element: 'multiselect'
          label: 'Tags'
          help: 'Choose relevant tags (optional)'
          alterable: false
          options: [
            'Agile',
            'Culture',
            'Design',
            'Events',
            'Innovation',
            'Lean',
            'Rails' ]

      - name: 'main_image'
        field:
          element: 'text'
          label: 'Main blog image URL'
          help: 'The image that is shown on the blog listing page (optional)'

      - name: 'date'
        field:
          element: 'text'
          value: CURRENT_DATETIME
          label: '* Date published'
          help: 'Must be in the format YYYY-MM-DD HH-MM (required)'

      - name: 'published'
        field:
          element: 'checkbox'
          value: true
          label: 'Published?'

      - name: 'layout'
        field:
          element: 'hidden'
          value: 'blog'
```

Produces:
```YML
---
layout: blog
author: Tom Sabin
tags: 
  - Agile
main_image: "https://upload.wikimedia.org/wikipedia/commons/1/1e/Large_Siamese_cat_tosses_a_mouse.jpg"
date: "2015-10-16 11:41 +0100"
published: true
title: Blog post title
---
```

Should there really be a limit on the number of fields you can include in the config file?
