### ISSUE TITLE
Empty list for multiselect showing `null` as select item

### ISSUE THREAD

**Issue by tomsabin** [prose/prose#894]
When a multiselect has no items selected (i.e. it produces `tags: null`) this is shown as an item when editing an article:

<img width="288" alt="screen shot 2015-10-16 at 11 49 55" src="https://cloud.githubusercontent.com/assets/885223/10540172/8a8c03ba-73fd-11e5-8e08-08c3c4af20ea.png">

Config:

```YML
...
- name: 'tags'
  field:
    element: 'multiselect'
    label: 'Tags'
    help: 'Choose relevant tags (optional)'
    alterable: false
    options: [
      'Foo'
      'Bar'
      'Baz']
```
