### ISSUE TITLE
Metadata for select form field shows first list item instead of actual value

### ISSUE THREAD

**Issue by tmfrnz** [prose/prose#944]
When providing multiple options for a select dropdown metadata form field the value shown on the metadata view is always the first item in the option list and not the actual value stored as the frontmatter attribute.

This happened regardless of "placeholder" attribute set, in multiple repositories I tested this, and both when specifying an options list above the prose settings, eg
```
languages: &languages
  - name: 'English'
    value: 'en'
  - name: 'French'
    value: 'fr'
```
and referring to it in the prose metadata config with
```
      - name: "lang"
        field:
          element: "select"
          label: "Select language"
          options: *languages 
```
as well when specifying the options straight in the prose config, like
```
      - name: "lang"
        field:
          element: "select"
          label: "Select language"
          options: 
            - name: 'English'
              value: 'en'
            - name: 'French'
              value: 'fr'
```

(OS Windows 7 Professional, Browser Chrome 49)
