### ISSUE TITLE
CURRENT_DATETIME in metafields

### ISSUE THREAD

**Issue by rcemtl** [prose/prose#980]
Hi!
I’m having the config:

```yml
prose:
  metadata:
    - name: "when"
        field:
          element: "text"
          label: "When"
          help: "The date of the event"
          placeholder: CURRENT_DATETIME
          type: "datetime"
```

but it does not insert the date, instead just outputs `CURRENT_DATETIME` text.
Is there anything I can do about it?
Thanks.

**Comment by dereklieu** [comment]
@rcemtl You almost got it, but you need to put CURRENT_DATETIME as the value and not the placeholder.

```yml
prose:
  metadata:
    - name: "when"
        field:
          element: "text"
          label: "When"
          help: "The date of the event"
          value: CURRENT_DATETIME
          type: "datetime"
```
