### ISSUE TITLE
Field with CURRENT_DATETIME is not updated upon changing the document

### ISSUE THREAD

**Issue by drdaemos** [prose/prose#994]
The problem is in the subject and I believe that this var should be updated, otherwise CURRENT_DATETIME is not useful at all.
I have similar prose config in Jekyll site:
```yaml
prose:
  metadata:
    en:
      - name: "updated_at"
        field:
          element: "hidden"
          value: CURRENT_DATETIME
```

When i'm creating the file, CURRENT_DATETIME works perfectly fine, but not when updating.
